name: MacOS Package

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.target[0] }}
    strategy:
      matrix:
        target:
          - [macos-13, manylinux_x86_64]
          - [macos-14, macosx_arm64]
        python:
          - cp312

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Build wheels using cibuildwheel
        uses: pypa/cibuildwheel@ee63bf16da6cddfb925f542f2c7b59ad50e93969 # v2.22.0
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.target[1] }}
          CIBW_BUILD_VERBOSITY: 1
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
